
# Example usage in playbooks


- name: check dns is available
  hosts: source
  tasks:
    - import_role:
        name: tcp_check
      vars:
        target_nodes:  "{{ groups['target0'] }}"
        tcp_ports: [22]
    - import_role:
        name: udp_check
      vars:
        target_nodes:  "{{ groups['target1'] }}"
        udp_ports: [53,123]
        do_nmap_udp: True
    - import_role:
        name: curl_check
      vars:
        target_nodes:  "{{ groups['target2'] }}"
        do_curl: True
        curl_ports: [80,8080,9090]

- name: check for errors (fail if any)
  hosts: source
  tasks:
    - import_role:
        name: check_errors
