
# Example usage in playbooks

- name: init values
  hosts: source
  gather_facts: no
  become_method: sudo
  tasks:
    - import_role:
        name: init_values

- name: checks
  hosts: source
  tasks:
    - import_role:
        name: ping_check
      vars:
        target_nodes:  "{{ groups['target1'] }}"
        #target_nodes:  "{{ comma-separeted-stringvar.split(',') }}"
    - import_role:
        name: tcp_check
      vars:
        target_nodes:  "{{ groups['target2'] }}"
        tcp_ports: [22]
    - import_role:
        name: udp_check
      vars:
        target_nodes:  "{{ groups['target3'] }}"
        udp_ports: [53,123]
        do_nmap_udp: True
    - import_role:
        name: curl_check
      vars:
        target_nodes:  "{{ groups['target4'] }}"
        curl_ports: [80,8080,9090]

- name: check for errors (fail if any)
  hosts: source
  tasks:
    - import_role:
        name: check_errors
