
# Example usage in playbooks


- name: check dns is available
  hosts: source
  tasks:
    - import_role:
        name: portchecker_run_checks
      vars:
        target_nodes:  "{{ groups['target1'] }}"
        udp_ports: [53]
        #do_nmap_udp: True

- name: check registry is available
  hosts: source
  tasks:
    - import_role:
        name: portchecker_run_checks
      vars:
        target_nodes:  "{{ groups['target2'] }}"
        do_curl: True
        curl_ports: [5000]

- name: check http server is available
  hosts: source
  tasks:
    - import_role:
        name: portchecker_run_checks
      vars:
        target_nodes:  "{{ groups['target3'] }}"
        do_curl: True
        curl_ports: [80]

# etc ...

- name: check for errors (fail if any)
  hosts: source
  tasks:
    - import_role:
        name: portchecker_check_errors


