---

#run listeners on target nodes if needed (when run_listeners == True)
- name: run listeners
  hosts: "{{ target_list is defined | ternary( target_list , target_groupname | default('target')) }}"
  gather_facts: no
  become_method: sudo
  tasks:
    - import_role:
        name: portchecker_run_listeners

  #check ports on target nodes from source nodes (tcp/udp, http)
- name: run checks
  hosts: "{{ source_list is defined | ternary( source_list , source_groupname | default('source')) }}"
  gather_facts: no 
  become_method: sudo
  tasks:
    - import_role:
        name: portchecker_run_checks
      vars:
        target_nodes:  "{{ target_list is defined | ternary( target_list , groups[target_groupname | default('target')] ) }}"
        #...

  #cleanup if listeners were used. can be skipped with do_cleanup=False
- name: cleanup
  hosts: "{{ target_list is defined | ternary( target_list , target_groupname | default('target')) }}"
  gather_facts: no
  become_method: sudo
  tasks:
    - import_role:
        name: portchecker_run_cleanup

  # fail if there were errors during the checks
- name: fail on errors
  hosts: "{{ source_list is defined | ternary( source_list , source_groupname | default('source')) }}"
  gather_facts: no
  tasks:
    - import_role:
        name: portchecker_check_errors

