---

#run checks
- name: curl check
  shell: curl {{ curl_opts | default("-k -m5") }} {{ curl_protocol | default("http") }}://{{ item.0 }}:{{ item.1 }}
  loop: "{{ target_nodes|product(curl_ports|default([]))|list }}"
  register: curl_get
  ignore_errors: yes

#set host facts on check errors
- set_fact:
    curl_error: True
  when: item.rc != 0
  loop: "{{ curl_get.results }}"

#print failed checks
- name: show failed curl gets
  debug:
    msg: "FAILED CURL: the curl command ({{ item.cmd }}) has failed"
  when: item.rc != 0
  loop: "{{ curl_get.results }}"


...
